### ISSUE TITLE
Missing FileKMLViewController.h?

### ISSUE THREAD

**Issue by NightFlyer** [MavEtJu/Geocube#10]
Commit https://github.com/MavEtJu/Geocube/commit/a329f6cc609cb8192d32900550bccd7f3624a2e2 has Geocube/Geocube-Prefix.pch which references 'FileKMLViewController.h', but that file isn't in the release as far as I can tell.

**Comment by NightFlyer** [comment]
Also FileKMLViewController.m is referenced from the project, but isn't in the release.

**Comment by MavEtJu** [comment]
An overzealous ignore statement in my .git directory caused this. Apologies, fixed now.
